name: CI

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/setup-and-cache

            - name: Install & Build
              run: |
                  yarn install
                  yarn build

            - name: Lint
              run: yarn lint

            - name: Unit Test
              run: yarn test

            - name: Docs Test
              run: yarn test:docs

            - name: Component Test
              uses: cypress-io/github-action@v2
              with:
                  command: yarn test:component
                  config-file: config/cypress/cypress.json

            - name: Integration Test
              uses: cypress-io/github-action@v2
              with:
                  install: false
                  command: yarn test:integration
                  config-file: test/integration/cypress.json
