name: End to end tests

on:
    workflow_dispatch:
    workflow_run:
        workflows:
            - Deploy
        types:
            - completed

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/setup-and-cache

            - name: Install
              run: yarn install

            - name: End to end Test
              uses: cypress-io/github-action@v4
              with:
                  command: yarn test:e2e
                  config-file: test/end-to-end/cypress.config.ts
